info:
  version: 1.0.0
  title: OpenAPI3
  name: openapi3
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    rate-limits:
      default:
        value: 100/1hour
    title: Default Plan
    description: Default Plan
    approval: false
apis:
  psd2api:
    $ref: psd2-api_v2.yaml
visibility:
  view:
    type: public
    orgs: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    enabled: true
product: 1.0.0
